[package]
org = "finance"
name = "finance_mis_integration"
version = "0.1.0"

[build-options]
observabilityIncluded = true

# Add the PostgreSQL dependency
[[platform.java11.dependency]]
groupId = "org.postgresql"
artifactId = "postgresql"
version = "42.6.0"