[package]
org = "atheeque"
name = "finance_backend"
version = "0.1.0"
distribution = "2201.8.6"

[platform.java17]
[[platform.java17.dependency]]
path = "lib/mysql-connector-j-9.4.0/mysql-connector-j-9.4.0.jar"
